#!/usr/bin/env python3
# -*- mode: python -*-

# Copyright (C) 2011 Chris Dekter
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import os, sys
import faulthandler;faulthandler.enable()

# remove WINDOWID environment variable so that zenity is not tied to the window from which it was launched.
try: del os.environ['WINDOWID']
except KeyError: pass

from autokey.gtkapp import Application

a = Application()
a.main()
sys.exit(0)
