---
name: Bug
description: >
  Thank you for taking the time to help out the AutoKey project!
  Click the "Get started" button to file your bug/issue report.
labels: [bug, help wanted]
assignees: Elliria
body:
  # EXISTING ISSUE
  - type: checkboxes
    id: existing-issue
    attributes:
      label: Has this issue already been reported?
      description: >
        "Please [check](https://github.com/autokey/autokey/issues)
        if a bug report already exists for your issue. If there is
        one, consider contributing to it instead. If there isn't
        one, check this box and continue filling out this form."
      options:
        - label: "I have searched through the existing issues."
          required: true
  # CLASSIFICATION
  - type: dropdown
    id: classification
    attributes:
      label: What type of issue is this?
      multiple: false
      options:
        - Bug
        - Crash/Hang/Data loss
        - Enhancement
        - Feature (new)
        - Performance
        - UI/Usability
    validations:
      required: false
  # REPRODUCIBILITY
  - type: dropdown
    id: reproducibility
    attributes:
      label: Can this be reproduced?
      description: null
      multiple: false
      options:
        - Always
        - I didn't try
        - Rarely
        - Sometimes
        - Unable
    validations:
      required: false
  # LINUX DISTRIBUTION
  - type: textarea
    id: linux-distribution
    attributes:
      label: Which Linux distribution did you use?
      description: >
        Provide information about your Linux distribution and its
        release or version number.
    validations:
      required: false
  # AUTOKEY VERSION
  - type: textarea
    id: autokey-version
    attributes:
      label: Which AutoKey version did you use?
      description: >
        Paste in your AutoKey version and, if the problem is known
        to be present in more than one version, please list them all.
    validations:
      required: false
  # GUI
  - type: dropdown
    id: gui
    attributes:
      label: Which GUI did you use?
      multiple: false
      options:
        - GTK
        - Qt
        - Both
    validations:
      required: false
  # INSTALLED VIA
  - type: dropdown
    id: installation-method
    attributes:
      label: How did you install AutoKey?
      multiple: false
      options:
        - Git
        - package manager
        - pip3
        - PPA
    validations:
      required: false
  # SUMMARY
  - type: textarea
    id: summary
    attributes:
      label: Can you describe the issue?
      description: Provide a brief summary of the problem.
    validations:
      required: false
  # STEPS TO RREPRODUCE
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: What are the steps to reproduce the issue?
      description: >
        "Provide the steps that need to be taken to reproduce the
        behavior. For example:"
      placeholder: |
        1. Do this.
        2. Then do that.
        3. Then do this other thing.
    validations:
      required: false
  # EXPECTED RESULT
  - type: textarea
    id: expected-result
    attributes:
      label: "Expected result:"
      description: Provide a description of what you expected to happen.
    validations:
      required: false
  # ACTUAL RESULT
  - type: textarea
    id: actual-result
    attributes:
      label: Current Behavior
      description: Provide a description of what actually happened.
    validations:
      required: false
  # SCREENSHOT
  - type: textarea
    id: screenshot
    attributes:
      label: Screenshot
      description: >
        Include one or more screenshots of the issue, if applicable,
        by dragging the image file(s) here to help with debugging.
    validations:
      required: false
  # VERBOSE OUTPUT
  - type: textarea
    id: verbose-output
    attributes:
      label: Can you provide the output of the AutoKey command?
      description: >
        "Start AutoKey in verbose mode from a terminal window with
        either the `autokey-gtk --verbose` or `autokey-qt --verbose`
        command. Then do the minimum required to recreate your issue
        and close AutoKey. This will produce a log in the terminal
        window of what AutoKey did and may show you wnat is wrong.
        Copy the log from the terminal and paste it into a code block
        below, enclosing it in triple brackets above and below it."
      placeholder: |
        ```
        Example output.
        ```
    validations:
      required: false
  # NOTES
  - type: textarea
    id: notes
    attributes:
      label: Anything else?
      description: >
        Describe any debugging steps you've taken, a workaround you've
        figured out, or any other information you think we might need,
        including links or references.
    validations:
      required: false
...
