.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps.
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection.
.\" Other parameters are allowed: see man(7), man(1).
.TH AUTOKEY-GTK "1" "April 16, 2023"
.\" Please adjust this date whenever revising the man page.
.\"
.\" Some roff macros for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left-justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" For man-page-specific macros, see man(7).
.SH NAME
autokey-gtk \- keyboard automation utility for GNOME and GTK
.SH SYNOPSIS
.B autokey-gtk
.RI [ options ]
.SH DESCRIPTION
This manual page briefly documents the \fBautokey-gtk\fP command.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invoke bold-face or italics,
.\" respectively.
\fBautokey-qt\fP is a desktop automation utility for Linux and X11
that's customized for use in the GNOME and GTK environments. AutoKey
allows for the automation of virtually any task by responding to typed
abbreviations and hotkeys. It provides a full-featured GUI to make it
highly-accessible for novices and a scripting interface to offer the
full flexibility and power of the Python language.
.PP
See the online wiki at https://github.com/autokey/autokey/wiki for more
information.
.SH OPTIONS
This program follows the usual GNU command-line syntax in which long
options start with two dashes (`--').
A summary of options is included below.
.TP
.B \-c, \-\-configure
Show the main window on start-up or at any time while the program is
running.
.TP
.B \-\-cutelog-integration
Connect to a locally-running \fBcutelog\fP instance with default
settings to display the full program log.
.br
See the \fBcutelog\fP GitHub page at https://github.com/busimus/cutelog
for more information.
.TP
.B \-h, \-\-help
Show a summary of all options.
.TP
.B \-l, \-\-verbose
Enable verbose (debug) logging.
.TP
.B \-m, \-\-mouse
Enable verbose (debug) logging that includes mouse-button events.
.TP
.B \-V, \-\-version
Print the current AutoKey version to standard output and then exit.
.SH AUTHOR
AutoKey was written by Chris Dekter and was loosely based on a script by
Sam Peterson.
.PP
This manual page was written by Chris Dekter <cdekter@gmail.com>.
