#!/bin/sh

set -e

case "$1" in
    remove|deconfigure)
    if [ "$USER" = "root" ] && [ "${SUDO_USER:-$(logname)}" != "root" ]; then
        #  Remove the user from the "input" users group
        if [ -e /dev/uinput ]; then
            usermod -r -G "input" "${SUDO_USER:-$(logname)}"
        fi
        #  If Gnome is present, remove the Gnome Shell extension
        if command -v gnome-extensions >/dev/null 2>&1; then
            su -c 'gnome-extensions uninstall "autokey-gnome-extension@autokey"' "${SUDO_USER:-$(logname)}"
            rm -fr "/home/${SUDO_USER:-$(logname)}/.local/share/gnome-shell/extensions/autokey-gnome-extension@autokey"
        fi
    fi

    #  Remove non-root write access to /dev/uinput
    if [ -e /dev/uinput ]; then
        rm -f '/etc/udev/rules.d/10-autokey.rules'
        /usr/bin/udevadm control --reload
        /usr/bin/udevadm trigger --sysname-match='/devices/virtual/misc/uinput'
    fi
    ;;
esac

#DEBHELPER#

exit 0
