.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH AUTOKEY "1" "July 9, 2009"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
autokey \- keyboard automation utility
.SH SYNOPSIS
.B autokey
.RI [ -v | --verbose ]
.SH DESCRIPTION
This manual page briefly documents the
.B autokey
command.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics,
.\" respectively.
\fBautokey\fP is a text expansion/replacement and hotkey utility for Linux and X11.
It can receive keyboard events via several methods and uses X events to drive the expansions. 
It is designed to save time by automating repetitive typing tasks, among other things.
.br
For more information refer to the online manual at:
    http://autokey.wiki.sourceforge.net/
.SH OPTIONS
This program follows the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.
.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B \-v, \-\-verbose
Enable verbose (debug) logging.
.SH AUTHOR
AutoKey was written by Chris Dekter, loosely based on a script by Sam Peterson.
.PP
This manual page was written by Chris Dekter <cdekter@gmail.com>.
