#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Copyright (C) 2011 Chris Dekter
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


import sys
import os.path
import queue
import time
import dbus
from typing import NamedTuple, Iterable

from PyQt5.QtCore import QObject, QEvent, Qt, pyqtSignal
from PyQt5.QtGui import QCursor, QIcon
from PyQt5.QtWidgets import QMessageBox, QApplication

import autokey.model.script
from autokey import common
common.USING_QT = True

from autokey import service, monitor

import autokey.argument_parser
import autokey.configmanager.configmanager as cm
import autokey.configmanager.configmanager_constants as cm_constants

from autokey.qtui import common as ui_common
from autokey.qtui.notifier import Notifier
from autokey.qtui.popupmenu import PopupMenu
from autokey.qtui.configwindow import ConfigWindow
from autokey.qtui.dbus_service import AppService
from autokey.logger import get_logger, configure_root_logger
from autokey.UI_common_functions import checkRequirements, checkOptionalPrograms, create_storage_directories
import autokey.UI_common_functions as UI_common

# Add Wayland support
from pywayland.client import Display
from pywayland.protocol.wayland import WlRegistry, WlSeat
from pywayland.protocol.wayland import WlKeyboard, WlPointer
from pywayland.protocol.wayland import WlShm, WlCompositor
from pywayland.protocol.wayland import WlShell, WlShellSurface
from pywayland.protocol.wayland import WlSurface
from pywayland.protocol.wayland import WlOutput
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.wayland import WlDataDevice
from pywayland.protocol.wayland import WlDataDeviceManager
from pywayland.protocol.wayland import WlDataSource
from pywayland.protocol.wayland import WlDataOffer
from pywayland.protocol.way
