#!/usr/bin/env python
# coding=UTF-8
#
# Generated by pykdeuic4 from uic/recorddialog.ui on Sat Nov 28 00:31:27 2009
#
# WARNING! All changes to this file will be lost.
from PyKDE4 import kdecore
from PyKDE4 import kdeui
from PyQt4 import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtGui.QLabel(Form)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.recKeyboardButton = QtGui.QCheckBox(Form)
        self.recKeyboardButton.setObjectName("recKeyboardButton")
        self.verticalLayout.addWidget(self.recKeyboardButton)
        self.recMouseButton = QtGui.QCheckBox(Form)
        self.recMouseButton.setObjectName("recMouseButton")
        self.verticalLayout.addWidget(self.recMouseButton)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtGui.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.secondsSpinBox = KIntSpinBox(Form)
        self.secondsSpinBox.setProperty("value", QtCore.QVariant(5))
        self.secondsSpinBox.setObjectName("secondsSpinBox")
        self.horizontalLayout.addWidget(self.secondsSpinBox)
        self.label_3 = QtGui.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(kdecore.i18n("Form"))
        self.label.setText(kdecore.i18n("Record a keyboard/mouse macro"))
        self.recKeyboardButton.setText(kdecore.i18n("Record keyboard events"))
        self.recMouseButton.setText(kdecore.i18n("Record mouse events (experimental)"))
        self.label_2.setText(kdecore.i18n("Start recording after"))
        self.label_3.setText(kdecore.i18n("seconds"))

from PyKDE4.kdeui import KIntSpinBox
