#!/usr/bin/env python
# coding=UTF-8
#
# Generated by pykdeuic4 from uic/scriptpage.ui on Thu Jan  7 13:58:21 2010
#
# WARNING! All changes to this file will be lost.
from PyKDE4 import kdecore
from PyKDE4 import kdeui
from PyQt4 import QtCore, QtGui

class Ui_ScriptPage(object):
    def setupUi(self, ScriptPage):
        ScriptPage.setObjectName("ScriptPage")
        ScriptPage.resize(587, 581)
        self.verticalLayout_2 = QtGui.QVBoxLayout(ScriptPage)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scriptCodeEditor = Qsci.QsciScintilla(ScriptPage)
        self.scriptCodeEditor.setObjectName("scriptCodeEditor")
        self.verticalLayout_2.addWidget(self.scriptCodeEditor)
        self.settingsGroupbox = QtGui.QGroupBox(ScriptPage)
        self.settingsGroupbox.setObjectName("settingsGroupbox")
        self.verticalLayout = QtGui.QVBoxLayout(self.settingsGroupbox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.promptCheckbox = QtGui.QCheckBox(self.settingsGroupbox)
        self.promptCheckbox.setObjectName("promptCheckbox")
        self.verticalLayout.addWidget(self.promptCheckbox)
        self.showInTrayCheckbox = QtGui.QCheckBox(self.settingsGroupbox)
        self.showInTrayCheckbox.setObjectName("showInTrayCheckbox")
        self.verticalLayout.addWidget(self.showInTrayCheckbox)
        self.kseparator = KSeparator(self.settingsGroupbox)
        self.kseparator.setObjectName("kseparator")
        self.verticalLayout.addWidget(self.kseparator)
        self.settingsWidget = SettingsWidget(self.settingsGroupbox)
        self.settingsWidget.setObjectName("settingsWidget")
        self.verticalLayout.addWidget(self.settingsWidget)
        self.verticalLayout_2.addWidget(self.settingsGroupbox)

        self.retranslateUi(ScriptPage)
        QtCore.QMetaObject.connectSlotsByName(ScriptPage)

    def retranslateUi(self, ScriptPage):
        ScriptPage.setWindowTitle(kdecore.i18n("Form"))
        self.settingsGroupbox.setTitle(kdecore.i18n("Script Settings"))
        self.promptCheckbox.setText(kdecore.i18n("Always prompt before running this script"))
        self.showInTrayCheckbox.setText(kdecore.i18n("Show in tray menu"))

from PyQt4 import Qsci
from PyKDE4.kdeui import KSeparator
from configwindow import SettingsWidget
