#!/usr/bin/env python
# coding=UTF-8
#
# Generated by pykdeuic4 from scriptpage.ui on Wed Jul 22 13:32:04 2009
#
# WARNING! All changes to this file will be lost.
from PyKDE4 import kdecore
from PyKDE4 import kdeui
from PyQt4 import QtCore, QtGui

class Ui_ScriptPage(object):
    def setupUi(self, ScriptPage):
        ScriptPage.setObjectName("ScriptPage")
        ScriptPage.resize(587, 581)
        self.verticalLayout_2 = QtGui.QVBoxLayout(ScriptPage)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.descriptionLabel = QtGui.QLabel(ScriptPage)
        self.descriptionLabel.setObjectName("descriptionLabel")
        self.verticalLayout_2.addWidget(self.descriptionLabel)
        self.descriptionLineEdit = KLineEdit(ScriptPage)
        self.descriptionLineEdit.setObjectName("descriptionLineEdit")
        self.verticalLayout_2.addWidget(self.descriptionLineEdit)
        self.scriptCodeEditor = Qsci.QsciScintilla(ScriptPage)
        self.scriptCodeEditor.setObjectName("scriptCodeEditor")
        self.verticalLayout_2.addWidget(self.scriptCodeEditor)
        self.settingsGroupbox = QtGui.QGroupBox(ScriptPage)
        self.settingsGroupbox.setObjectName("settingsGroupbox")
        self.verticalLayout = QtGui.QVBoxLayout(self.settingsGroupbox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.settingsWidget = SettingsWidget(self.settingsGroupbox)
        self.settingsWidget.setObjectName("settingsWidget")
        self.verticalLayout.addWidget(self.settingsWidget)
        self.verticalLayout_2.addWidget(self.settingsGroupbox)

        self.retranslateUi(ScriptPage)
        QtCore.QMetaObject.connectSlotsByName(ScriptPage)

    def retranslateUi(self, ScriptPage):
        ScriptPage.setWindowTitle(kdecore.i18n("Form"))
        self.descriptionLabel.setText(kdecore.i18n("Description"))
        self.settingsGroupbox.setTitle(kdecore.i18n("Settings"))

from PyQt4 import Qsci
from configwindow import SettingsWidget
from PyKDE4.kdeui import KLineEdit
