#!/usr/bin/env python
# coding=UTF-8
#
# Generated by pykdeuic4 from uic/specialhotkeysettings.ui on Sat Aug  1 00:25:47 2009
#
# WARNING! All changes to this file will be lost.
from PyKDE4 import kdecore
from PyKDE4 import kdeui
from PyQt4 import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(531, 397)
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtGui.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.monitorKeyLabel = QtGui.QLabel(self.groupBox)
        self.monitorKeyLabel.setObjectName("monitorKeyLabel")
        self.horizontalLayout_2.addWidget(self.monitorKeyLabel)
        spacerItem = QtGui.QSpacerItem(269, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.setMonitorButton = KPushButton(self.groupBox)
        self.setMonitorButton.setObjectName("setMonitorButton")
        self.horizontalLayout_2.addWidget(self.setMonitorButton)
        self.clearMonitorButton = KPushButton(self.groupBox)
        self.clearMonitorButton.setObjectName("clearMonitorButton")
        self.horizontalLayout_2.addWidget(self.clearMonitorButton)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(Form)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.configKeyLabel = QtGui.QLabel(self.groupBox_2)
        self.configKeyLabel.setObjectName("configKeyLabel")
        self.horizontalLayout.addWidget(self.configKeyLabel)
        spacerItem1 = QtGui.QSpacerItem(269, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.setConfigButton = KPushButton(self.groupBox_2)
        self.setConfigButton.setObjectName("setConfigButton")
        self.horizontalLayout.addWidget(self.setConfigButton)
        self.clearConfigButton = KPushButton(self.groupBox_2)
        self.clearConfigButton.setObjectName("clearConfigButton")
        self.horizontalLayout.addWidget(self.clearConfigButton)
        self.verticalLayout.addWidget(self.groupBox_2)
        spacerItem2 = QtGui.QSpacerItem(20, 224, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(kdecore.i18n("Form"))
        self.groupBox.setTitle(kdecore.i18n("Toggle monitoring using a hotkey"))
        self.label.setText(kdecore.i18n("Hotkey: "))
        self.monitorKeyLabel.setText(kdecore.i18n("$hotkey"))
        self.setMonitorButton.setText(kdecore.i18n("Set"))
        self.clearMonitorButton.setText(kdecore.i18n("Clear"))
        self.groupBox_2.setTitle(kdecore.i18n("Show configuration window using a hotkey"))
        self.label_2.setText(kdecore.i18n("Hotkey: "))
        self.configKeyLabel.setText(kdecore.i18n("$hotkey"))
        self.setConfigButton.setText(kdecore.i18n("Set"))
        self.clearConfigButton.setText(kdecore.i18n("Clear"))

from PyKDE4.kdeui import KPushButton
