#!/usr/bin/env python
# coding=UTF-8
#
# Generated by pykdeuic4 from interfacesettings.ui on Sun Mar  4 11:39:40 2012
#
# WARNING! All changes to this file will be lost.
from PyKDE4 import kdecore
from PyKDE4 import kdeui
from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(533, 438)
        self.verticalLayout_3 = QtGui.QVBoxLayout(Form)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.groupBox = QtGui.QGroupBox(Form)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.xRecordButton = QtGui.QRadioButton(self.groupBox)
        self.xRecordButton.setObjectName(_fromUtf8("xRecordButton"))
        self.verticalLayout.addWidget(self.xRecordButton)
        self.xEvdevButton = QtGui.QRadioButton(self.groupBox)
        self.xEvdevButton.setObjectName(_fromUtf8("xEvdevButton"))
        self.verticalLayout.addWidget(self.xEvdevButton)
        self.atspiButton = QtGui.QRadioButton(self.groupBox)
        self.atspiButton.setObjectName(_fromUtf8("atspiButton"))
        self.verticalLayout.addWidget(self.atspiButton)
        self.verticalLayout_3.addWidget(self.groupBox)
        spacerItem = QtGui.QSpacerItem(20, 152, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(kdecore.i18n(_fromUtf8("Form")))
        self.groupBox.setTitle(kdecore.i18n(_fromUtf8("Interface Type")))
        self.label_2.setText(kdecore.i18n(_fromUtf8("Configure the method AutoKey uses to receive keyboard and mouse events. Only change this option if AutoKey is not responding to abbreviations and hotkeys.\n"
"\n"
"After changing this option, you will need to restart AutoKey for it to take effect.\n"
"")))
        self.xRecordButton.setText(kdecore.i18n(_fromUtf8("X Record - for X.org server v1.5 or v1.7.6 and above")))
        self.xEvdevButton.setText(kdecore.i18n(_fromUtf8("X EvDev - for X.org server from v1.6 to v1.7.5")))
        self.atspiButton.setText(kdecore.i18n(_fromUtf8("AT-SPI - fallback option for Gnome users")))

