#!/usr/bin/env python
# coding=UTF-8
#
# Generated by pykdeuic4 from uic/interfacesettings.ui on Sat Aug  1 00:31:21 2009
#
# WARNING! All changes to this file will be lost.
from PyKDE4 import kdecore
from PyKDE4 import kdeui
from PyQt4 import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(533, 438)
        self.verticalLayout_3 = QtGui.QVBoxLayout(Form)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtGui.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.xRecordButton = QtGui.QRadioButton(self.groupBox)
        self.xRecordButton.setObjectName("xRecordButton")
        self.verticalLayout.addWidget(self.xRecordButton)
        self.xEvdevButton = QtGui.QRadioButton(self.groupBox)
        self.xEvdevButton.setObjectName("xEvdevButton")
        self.verticalLayout.addWidget(self.xEvdevButton)
        self.atspiButton = QtGui.QRadioButton(self.groupBox)
        self.atspiButton.setObjectName("atspiButton")
        self.verticalLayout.addWidget(self.atspiButton)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, 10, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtGui.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.checkBox = QtGui.QCheckBox(Form)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_2.addWidget(self.checkBox)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        spacerItem = QtGui.QSpacerItem(20, 152, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(kdecore.i18n("Form"))
        self.groupBox.setTitle(kdecore.i18n("Interface Type"))
        self.label_2.setText(kdecore.i18n("Configure the method AutoKey uses to receive keyboard and mouse events. Only change this option if AutoKey is not responding to abbreviations and hotkeys.\n"
"\n"
"After changing this option, you will need to restart AutoKey for it to take effect.\n"
""))
        self.xRecordButton.setText(kdecore.i18n("X Record - Preferred option when using X.org server v1.5 or older"))
        self.xEvdevButton.setText(kdecore.i18n("X EvDev - Preferred option when using X.org server v1.6 or newer"))
        self.atspiButton.setText(kdecore.i18n("AT-SPI - Fallback option for Gnome users when other methods fail"))
        self.label_3.setText(kdecore.i18n("Enable this option only if you experience randomly garbled text in KDE4"))
        self.checkBox.setText(kdecore.i18n("Enable QT4 workaround"))

