#!/usr/bin/env python
# coding=UTF-8
#
# Generated by pykdeuic4 from settingswidget.ui on Wed Jul 22 17:41:06 2009
#
# WARNING! All changes to this file will be lost.
from PyKDE4 import kdecore
from PyKDE4 import kdeui
from PyQt4 import QtCore, QtGui

class Ui_SettingsWidget(object):
    def setupUi(self, SettingsWidget):
        SettingsWidget.setObjectName("SettingsWidget")
        SettingsWidget.resize(316, 91)
        self.gridLayout = QtGui.QGridLayout(SettingsWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtGui.QLabel(SettingsWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.abbrLabel = QtGui.QLabel(SettingsWidget)
        self.abbrLabel.setObjectName("abbrLabel")
        self.gridLayout.addWidget(self.abbrLabel, 0, 1, 1, 1)
        self.setAbbrButton = KPushButton(SettingsWidget)
        self.setAbbrButton.setObjectName("setAbbrButton")
        self.gridLayout.addWidget(self.setAbbrButton, 0, 3, 1, 1)
        self.clearAbbrButton = KPushButton(SettingsWidget)
        self.clearAbbrButton.setObjectName("clearAbbrButton")
        self.gridLayout.addWidget(self.clearAbbrButton, 0, 4, 1, 1)
        self.label_2 = QtGui.QLabel(SettingsWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.hotkeyLabel = QtGui.QLabel(SettingsWidget)
        self.hotkeyLabel.setObjectName("hotkeyLabel")
        self.gridLayout.addWidget(self.hotkeyLabel, 1, 1, 1, 1)
        self.setHotkeyButton = KPushButton(SettingsWidget)
        self.setHotkeyButton.setObjectName("setHotkeyButton")
        self.gridLayout.addWidget(self.setHotkeyButton, 1, 3, 1, 1)
        self.clearHotkeyButton = KPushButton(SettingsWidget)
        self.clearHotkeyButton.setObjectName("clearHotkeyButton")
        self.gridLayout.addWidget(self.clearHotkeyButton, 1, 4, 1, 1)
        self.label_3 = QtGui.QLabel(SettingsWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.windowFilterLabel = QtGui.QLabel(SettingsWidget)
        self.windowFilterLabel.setObjectName("windowFilterLabel")
        self.gridLayout.addWidget(self.windowFilterLabel, 2, 1, 1, 1)
        self.setFilterButton = KPushButton(SettingsWidget)
        self.setFilterButton.setObjectName("setFilterButton")
        self.gridLayout.addWidget(self.setFilterButton, 2, 3, 1, 1)
        self.clearFilterButton = KPushButton(SettingsWidget)
        self.clearFilterButton.setObjectName("clearFilterButton")
        self.gridLayout.addWidget(self.clearFilterButton, 2, 4, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)

        self.retranslateUi(SettingsWidget)
        QtCore.QMetaObject.connectSlotsByName(SettingsWidget)

    def retranslateUi(self, SettingsWidget):
        SettingsWidget.setWindowTitle(kdecore.i18n("Form"))
        self.label.setText(kdecore.i18n("Abbreviation:"))
        self.abbrLabel.setText(kdecore.i18n("$abbr"))
        self.setAbbrButton.setText(kdecore.i18n("Set&"))
        self.clearAbbrButton.setText(kdecore.i18n("Clear&"))
        self.label_2.setText(kdecore.i18n("Hotkey:"))
        self.hotkeyLabel.setText(kdecore.i18n("$hotkey"))
        self.setHotkeyButton.setText(kdecore.i18n("Set&"))
        self.clearHotkeyButton.setText(kdecore.i18n("Clear&"))
        self.label_3.setText(kdecore.i18n("Window Filter:"))
        self.windowFilterLabel.setText(kdecore.i18n("$filter"))
        self.setFilterButton.setText(kdecore.i18n("Set&"))
        self.clearFilterButton.setText(kdecore.i18n("Clear&"))

from PyKDE4.kdeui import KPushButton
