#!/usr/bin/env python
# coding=UTF-8
#
# Generated by pykdeuic4 from windowfiltersettings.ui on Wed Feb 29 20:25:39 2012
#
# WARNING! All changes to this file will be lost.
from PyKDE4 import kdecore
from PyKDE4 import kdeui
from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(400, 300)
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(Form)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.triggerRegexLineEdit = KLineEdit(Form)
        self.triggerRegexLineEdit.setUrlDropsEnabled(False)
        self.triggerRegexLineEdit.setProperty("showClearButton", True)
        self.triggerRegexLineEdit.setObjectName(_fromUtf8("triggerRegexLineEdit"))
        self.verticalLayout.addWidget(self.triggerRegexLineEdit)
        self.recursiveCheckBox = QtGui.QCheckBox(Form)
        self.recursiveCheckBox.setObjectName(_fromUtf8("recursiveCheckBox"))
        self.verticalLayout.addWidget(self.recursiveCheckBox)
        self.kseparator = KSeparator(Form)
        self.kseparator.setObjectName(_fromUtf8("kseparator"))
        self.verticalLayout.addWidget(self.kseparator)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(kdecore.i18n(_fromUtf8("Form")))
        self.label.setText(kdecore.i18n(_fromUtf8("Only trigger in windows with title/class matching:")))
        self.triggerRegexLineEdit.setToolTip(kdecore.i18n(_fromUtf8("Window title")))
        self.triggerRegexLineEdit.setWhatsThis(kdecore.i18n(_fromUtf8("Enter a regular expression that matches the title of windows in which you want this item to trigger.")))
        self.recursiveCheckBox.setText(kdecore.i18n(_fromUtf8("Apply recursively to subfolders and items")))

from PyKDE4.kdeui import KSeparator, KLineEdit
